# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 14:14
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170830_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleUE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='\u6807\u9898')),
                ('body', DjangoUeditor.models.UEditorField(blank=True, verbose_name='\u6b63\u6587')),
                ('date', models.DateTimeField(verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='\u5206\u7c7b')),
                ('tags', models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='\u6807\u7b7e')),
            ],
        ),
    ]
